import { type SchemaTypeDefinition } from 'sanity'
import destination from './destination'
import stickerVisa from './stickerVisa'
import tour from './tour'


import umrahDays from './umrahDays'
import makkahHotel from './makkahHotel'
import madinaHotel from './madinaHotel'
import fileConsultancy from './fileConsultancy'
import iran from './iran'
import hajj from './hajj'
import ticketing from './ticketing'
import offer from './offer'
import umrahOffer from './umrahOffer'
import hajjOffer from './hajjOffer'
import iranOffer from './iranOffer'
import user from './user'
import booking from './booking'
import visaBooking from './visaBooking'
import stickerVisaBooking from './stickerVisaBooking'
import fileBooking from './fileBooking'
import tourBooking from './tourBooking'
import hajjBooking from './hajjBooking'
import umrahBooking from './umrahBooking'
import iranBooking from './iranBooking'
import visaOfferBooking from './visaOfferBooking'
import iranOfferBooking from './iranOfferBooking'
import hajjOfferBooking from './hajjOfferBooking'
import umrahOfferBooking from './umrahOfferBooking'
import makkahHotelImg from './makkahHotelImg'
import madinaHotelImg from './madinaHotelImg'
import bank from './bank'
import umrahAvailability from './umrahAvailability'
import hajjAvailability from './hajjAvailability'

export const schema: { types: SchemaTypeDefinition[] } = {
  types: [user,bank,booking, destination, stickerVisa, tour, fileConsultancy, umrahAvailability ,umrahDays, makkahHotel,makkahHotelImg, madinaHotel ,madinaHotelImg,  iran, hajjAvailability,hajj, ticketing, offer, umrahOffer,hajjOffer, iranOffer,stickerVisaBooking, visaBooking,fileBooking,tourBooking,hajjBooking,umrahBooking,iranBooking,visaOfferBooking,iranOfferBooking,hajjOfferBooking,umrahOfferBooking, ],
}
