

export interface Destination {
    _id: string,
    countryName: string,
    prize: number,
    requirements:string,
    requirement1:string,
    requirement2:string,
    requirement3:string,
    requirement4:string,
    requirement5:string,
    requirement6:string,
    requirement7:string,
    requirement8:string,
    requirement9:string,
    requirement10:string,
    requirement11:string,
    requirement12:string,
    requirement13:string,
    requirement14:string,
    requirement15:string,
    requirement16:string,
    requirement17:string,
    imageUrl2: string,
    imageUrl3: string,
    imageUrl :string,
    shortDescription: string,
    
    rating: number,
    availability: "Available" | "Coming Soon",
}

export interface TourType {
    _id: string,
    countryName: string,
    prize: number,
    shortDescription: string,
   
    tourIncludeHeading: string,
    tourInclude1: string,
    tourInclude2: string,
    tourInclude3: string,
    tourInclude4: string,
    tourInclude5: string,
    tourInclude6: string,
    tourInclude7: string,
    tourInclude8: string,
    tourInclude9: string,
    heading1: string,
    day1:string,
    heading2: string,
    day2:string,
    heading3: string,
    day3:string,
    heading4: string,
    day4:string,
    heading5: string,
    day5:string,
    heading6: string,
    day6:string,
    heading7: string,
    day7:string,
    heading8: string,
    day8:string,
    heading9: string,
    day9:string,
    requirementsH: string,
    requirement1:string,
    requirement2:string,
    requirement3:string,
    requirement4:string,
    requirement5:string,
    requirement6:string,
    imageUrl :string,
    imageUrl2: string,
    imageUrl3: string,
    imageUrl4: string,
    
    
}


export interface UmrahType{
    _id:string,
    countryName:string,
    shortDescription:string,
    prize:number,
    requirements:string,
    requirement1:string,
    imageUrl :string,
    imageUrl2: string,
    imageUrl3: string,
}


export interface HajjType{
    _id:string,
    countryName:string,
    shortDescription:string,
    dayDuration: string,
    requirements:string,
    requirement1:string,
    imageUrl :string,
    imageUrl2: string,
    imageUrl3: string,
    hajjDaysH:string,
    hajjDays:string,
    azizaBuildingH:string,
    azizaBuildingDays:string,
    maktab:string,
    maktabZone:string,
    makkahHotelH:string,
    makkahHotel1:string,
    makkahHotelDays:string,
    makkahHotel2:string,
    makkahHotel3:string,
    madinaHotelH:string,
    madinaHotelName: string,
    madinaHotelDays:string,
    sharingH:string,
    sharingPrize:number,
    tripleBedH:string,
    tripleBedPrize:number,
    doubleBedH:string,
    doubleBedPrize:number,
    includeH:string,
    include1:string,
    include2:string,
    include3:string,
    include4:string,
    include5:string,
    include6:string,
    include7:string,
    ziaratH:string,
    ziaratText:string,
    desc1:string,
    desc2:string,
    desc3:string,
    desc4:string
}