import { defineQuery } from "next-sanity";

export const detailCountry = defineQuery(`*[_type == "stickerVisa"  && _id == $id][0]{
   _id,
  countryName,
  requirements,
requirement1,
requirement2,
requirement3,
requirement4,
requirement5,
requirement6,
requirement7,
requirement8,
requirement9,
requirement10,
requirement11,
requirement12,
requirement13,
requirement14,
requirement15,
supportiveDoc,
requirement16,
requirement17,
requirement18,
requirement19,
requirement20,
requirement21,
  "imageUrl": image.asset->url,
   "imageUrl2": image2.asset->url,
    "imageUrl3": image3.asset->url,
  prize,
  priceForUsers,
  shortDescription,

  availability
}`)
export const detailCountryEVisa = defineQuery(`*[_type == "destinations"  && _id == $id][0]{
  _id,
 countryName,
 requirements,
 requirement1,
 requirement2,
 requirement3,
 requirement4,
 requirement5,
 requirement6,
 requirement7,
 requirement8,

 "imageUrl": image.asset->url,
  "imageUrl2": image2.asset->url,
   "imageUrl3": image3.asset->url,
 prize,
 prizeForUsers,
 shortDescription,
rating,
 availability
}`)
export const allDestinations = defineQuery(`*[_type == "destinations"]{
  _id,
  countryName,
  "imageUrl": image.asset->url,
    requirements,
  requirement1,

  "imageUrl": image.asset->url,
   "imageUrl2": image2.asset->url,
    "imageUrl3": image3.asset->url,
  prize,
  prizeForUsers,
  shortDescription,
 rating,
  availability
}`)


export const featuredestinations = defineQuery(`*[_type == "destinations"][5..12]{
  _id,
  countryName,
  "imageUrl": image.asset->url,
  prize,
  prizeForUsers,
  shortDescription,
 rating,
  availability
}`)

export const stickerVisa = defineQuery(`*[_type == "stickerVisa"]{
  _id,
  countryName,
    requirements,
  "imageUrl": image.asset->url,
   "image2": image.asset->url,
    "image3": image.asset->url,
  "imageUrl": image.asset->url,
  prize,
  priceForUsers,
  shortDescription,
  availability
  
  }`)

  export const tourPackage = defineQuery(`*[_type == "tour"]{
    _id,
    countryName,
    prize,
    priceForUsers,
    shortDescription,
    tourIncludeHeading,
    tourInclude1,
    tourInclude2,
    tourInclude3,
    tourInclude4,
    tourInclude5,
    tourInclude6,
    tourInclude7,
    tourInclude8,
    tourInclude9,
    heading1,
    day1,
    heading2,
    day2,
    heading3,
    day3,
    heading4,
    day4,
    heading5,
    day5,
    heading6,
    day6, 
    heading7,
    day7,
    heading8,
    day8,
    heading9,
    day9,
    "imageUrl": image.asset->url,
     "imageUrl2": image2.asset->url,
      "imageUrl3": image3.asset->url,
      "imageUrl4": image4.asset->url
    
   
    
    }`)

    export const tourDetailQuery = defineQuery(`*[_type == "tour"  && _id == $id][0]{
       _id,
    countryName,
    prize,
    priceForUsers,
    shortDescription,
    requirement1,
    requirement2,
    requirement3,
    requirement4,
    requirement5,
    requirement6,
    tourIncludeHeading,
    tourInclude1,
    tourInclude2,
    tourInclude3,
    tourInclude4,
    tourInclude5,
    tourInclude6,
    tourInclude7,
    tourInclude8,
    tourInclude9,
    heading1,
    day1,
    heading2,
    day2,
    heading3,
    day3,
    heading4,
    day4,
    heading5,
    day5,
    heading6,
    day6, 
    heading7,
    day7,
    heading8,
    day8,
    heading9,
    day9,
    
    "imageUrl": image.asset->url,
     "imageUrl2": image2.asset->url,
      "imageUrl3": image3.asset->url,
      "imageUrl4": image4.asset->url
   }`)
  

   export const fileAndConsultancy = defineQuery(`*[_type == "fileConsultancy"]{
    _id,
    countryName,
    prize,
    prizeForUsers,
    requirements,
    requirement1,
    "imageUrl": image.asset->url,
    "imageUrl2": image2.asset->url,
    "imageUrl3": image3.asset->url,
    shortDescription
  }`)

  export const fileAndConsultancyDetail = defineQuery(`*[_type == "fileConsultancy"  && _id == $id][0]{
    _id,
   countryName,
   requirements,
 requirement1,
 requirement2,
 requirement3,
 requirement4,
 requirement5,
 requirement6,
 requirement7,
 requirement8,
 requirement9,
 requirement10,
 requirement11,
 requirement12,
 requirement13,
 requirement14,
 requirement15,
 supportiveDoc,
 requirement16,
 requirement17,
 requirement18,
 requirement19,
 requirement20,
 requirement21,
  requirement22,
   requirement23,
    requirement24,
   "imageUrl": image.asset->url,
    "imageUrl2": image2.asset->url,
     "imageUrl3": image3.asset->url,
   prize,
   prizeForUsers,
   shortDescription
 }`)



 export const iranZiyarat = defineQuery(`*[_type == "iranIraq"] | order(_createdAt asc){
  _id,
  countryName,
  prize,
  priceForUsers,
  shortDescription,
  tourIncludeHeading,
  tourInclude1,
  tourInclude2,
  tourInclude3,
  tourInclude4,
 
  "imageUrl": image.asset->url,
   "imageUrl2": image2.asset->url
  }`)


  export const hajjPack = defineQuery(`*[_type == "hajjPackage"] | order(_createdAt desc){
    _id,
    countryName,
    prize1,
    sharingPriceForUsers,
     prize2,
     triplePriceForUsers,
      prize3,
      doublePriceForUsers,
    azizaStay2,
    azizaStayDetail2,
      makkahHotelH,
    makkahHotel,
    madinaHotelH,
    madinaHotel,
    foodHead,
    food,
    transportHead,
    transport,
    holyZiaratHead,
    holyziarat,
    ticketHead,
    airlineName,
    dep,
    flightNum1,
    dateOfFlight1,
    route1,
    time1,
    return,
    flightNum2,
    dateOfFlight2,
    route2,
    time2,
    azizaStay,
    azizaStayDetail,
    makkahStay,
    makkahStayDetail,
    madinaStay,
    madinaStayDetail,
    documentsH,
    doc1,
    doc2,
    doc3,
    doc4,
    doc5,
    doc6,
    "airlineImage" : airlineImage.asset->url,
    shortDescription,
    "imageUrl": image.asset->url,
     "imageUrl2": image2.asset->url
    }`)


    export const hajjFeature = defineQuery(`*[_type == "hajjFeatures"]{
    _id,
    azizaStay2,
    azizaStayDetail2,
      makkahHotelH,
    makkahHotel,
    madinaHotelH,
    madinaHotel,
    foodHead,
    food,
    transportHead,
    transport,
    holyZiaratHead,
    holyziarat,
    ticketHead,
    airlineName,
    dep,
    flightNum1,
    dateOfFlight1,
    route1,
    time1,
    return,
    flightNum2,
    dateOfFlight2,
    route2,
    time2,
    azizaStay,
    azizaStayDetail,
    makkahStay,
    makkahStayDetail,
    madinaStay,
    madinaStayDetail,
    documentsH,
    doc1,
    doc2,
    doc3,
    doc4,
    doc5,
    doc6,
    "airlineImage" : airlineImage.asset->url,
    }`


    )